### ISSUE TITLE
Error in Delete for the ResourceClient for empty resource list

### ISSUE THREAD

**Issue by andersjarl** [lithnet/resourcemanagement-client#11]
In the latest version there is a problem with the Delete function in the ResourceClient class which will give you an ArgumentNullException for an empty list of ResourceObject or empty list of UniqueIdentifier.
The code looks like this:
```
        public void Delete(IEnumerable<ResourceObject> resources)
        {
            if (resources == null)
            {
                throw new ArgumentNullException(nameof(resources));
            }
            // .....
        }

        public void Delete(IEnumerable<UniqueIdentifier> resourceIDs)
        {
            if (resourceIDs == null)
            {
                throw new ArgumentNullException(nameof(resourceIDs));
            }
            // .....
       }
```

The code before the latest version didn't check for null, but it did check for an empty list:
```
        public void Delete(IEnumerable<UniqueIdentifier> resourceIDs)
        {
            if (!resourceIDs.Any())
            {
                return;
            }
            // .....
        }
```

I recommend that when it's an empty list it will, just as before, return and do nothing, and when it's null throw an exception. This will make old code behave as it did before and not break.

**Comment by ryannewington** [comment]
Hi @andersjarl,

Agreed this is a regression issue. Updated the latest build and added unit tests to cover this scenario.

Thanks for reporting the bug.

Ryan
