### ISSUE TITLE
Missing OSS License File

### ISSUE THREAD

**Issue by NileshGhodekar** [lithnet/resourcemanagement-client#13]
Hi Ryan, can you please clarify under what license this project is open sourced? And to that effect, can you please include the license file in this repo? Thanks!

**Comment by ryannewington** [comment]
Hi @NileshGhodekar,

Thanks for pointing this out, I've added the MIT license file to the project.

Ryan

**Comment by NileshGhodekar** [comment]
Thanks Ryan! This makes it easy for recommending and adopting in customer engagements. Can I put a link to this and the PowerShell repo in the [Related Projects](https://github.com/Microsoft/MIMWAL/wiki/Related-Projects) wiki of MIMWAL?
