### ISSUE TITLE
Issue with XPATH query using 'contains'

### ISSUE THREAD

**Issue by MWOITC** [lithnet/resourcemanagement-client#16]
HI Ryan,

Using the latest version of the resourcemanagement client for .Net (1.0.6623.18312) and ran into an issue when using XPATH and 'contains'. The XPATH expression used would be something like "/Person[(contains(DisplayName, 'peter'))]. In .Net this generates a "Request could not be dispatched"  error.

I tried the same query in PowerShell and in there it fails too with the same error. If I change 'contains' to 'starts-with' it works (but that ofcourse doesn't give me all the objects I'm after).

Thanks
Mike

**Comment by ryannewington** [comment]
Hi Mike,

I've run this exact query on my environment and it works. I can and paste your xpath as well and that works too.

```
/Person[(contains(DisplayName, 'peter'))]
```

There might be a problem on the MIM Service processing the request. Do you have another environment you can test the query against?

Ryan

**Comment by MWOITC** [comment]
Hi Ryan,

Have run:
$query = New-XPathQuery -AttributeName DisplayName -Operator StartsWith -Value "annabel"
$expression =  New-XPathExpression -ObjectType Person -QueryObject $query
$expression.ToString()  -> /Person[(starts-with(DisplayName, 'annabel'))]
Get-ResourceCount -XPath $expression.ToString()
which results in "42"

$query = New-XPathQuery -AttributeName DisplayName -Operator Contains -Value "annabel"
$expression =  New-XPathExpression -ObjectType Person -QueryObject $query
$expression.ToString() -> /Person[(contains(DisplayName, 'annabel'))]
Get-ResourceCount -XPath $expression.ToString()
which generates the error:

Get-ResourceCount : Failure Message: 
Failure Source: Other
Details: Request could not be dispatched.
Correlation ID:3138a10d-9712-473f-b08e-9d6b092405e0
At line:9 char:1
+ Get-ResourceCount -XPath $expression.ToString()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ResourceCount], UnwillingToPerformException
    + FullyQualifiedErrorId : Lithnet.ResourceManagement.Client.UnwillingToPerformException,Lithnet.ResourceManagemen 
   t.Automation.GetResourceCount

Ran this code on both the server running the MIM portal and on a separate server using the "set-resourcemanagementclient". Both give the same result/error.

**Comment by ryannewington** [comment]
The UnwillingToPerformException is coming from the MIM Service itself. Do the event logs on the MIM service give any clues as to why it is rejecting this search request.

**Comment by MWOITC** [comment]
Should have done that in the first place......error is referring to SQL FullText filter daemon.  Had a look on an old test system and saw that that daemon was running where in the PROD system it was not. Looking at the cause of that now. SQL error log is pointing to an issue with the MIMService db - to be more precise the full text search.  That might explain why searching using 'starts-with' works but using 'contains' (full text search) fails..
Will get that fixed first and test again.

**Comment by ryannewington** [comment]
Interesting. Haven' seen that one before! let me know how you go

**Comment by MWOITC** [comment]
Hi Ryan, sorry for late reply - have been on leave.
Issue was indeed cuased by SQL's full text daemon not running and therefore a full text search wasn't possible. All good now.
