### ISSUE TITLE
GetResourcesPaged returns nothing

### ISSUE THREAD

**Issue by hoetz** [lithnet/resourcemanagement-client#17]
Our MIM Version is 4.4.1749.0
I was able to successfully establish a connection with the ResourceManagementClient and the proper credentials of our mim service account.
However, when searching for resources, I get only empty results and no errors.

For example this snippet returns an empty result:

```
string query = String.Format("/{0}[starts-with('{1}', 'k')]", "Person", AttributeNames.AccountName);
List<string> attributesToGet = new List<string>() { AttributeNames.AccountName };
List<SortingAttribute> sortAttributes = new List<SortingAttribute>();
sortAttributes.Add(new SortingAttribute("AccountName", true));
var res = client.GetResourcesPaged(query, 5,attributesToGet,sortAttributes);
```

When I run this query in the MIM metaverse search I get hundreds of results.

**Comment by ryannewington** [comment]
Hi @hoetz 

I've run your code in my environment and it returns the results as expected.

The MIM XPath doesn't call for quotes around the attribute name, so you can try it without
```
string query = String.Format("/{0}[starts-with({1}, 'k')]", "Person", AttributeNames.AccountName);
```
but both versions worked for me.

Do queries that don't use start-with work? For example a simple equals statement? Sometimes problems with the full-text indexer on the SQL side can cause starts-with and contains operations to behave inconsistently.

From a code perspective, you are structuring and generating the correct query.

**Comment by hoetz** [comment]
FWIW I also tried client.GetResourceByKey("Person", "AccountName", "myaccount") and I get a null result, no exception.

**Comment by ryannewington** [comment]
@hoetz the only thing I can think of that leads to that behavior is an MPR/permission issue. How are you authenticating as the service account?

**Comment by hoetz** [comment]
@ryannewington I am authenticating this way:

`System.Net.NetworkCredential creds = new System.Net.NetworkCredential("mimadmin", "password", "domain");
            Lithnet.ResourceManagement.Client.ResourceManagementClient client = new Lithnet.ResourceManagement.Client.ResourceManagementClient(creds)`

If I fail to provide valid credentials I get an error at once. The service account used is the same we use for the MIM Gui.

**Comment by ryannewington** [comment]
@hoetz what version of MIM are you running? Can you enable tracing?
If you are on the latest version you can use this
https://docs.microsoft.com/en-us/microsoft-identity-manager/infrastructure/mim-service-dynamic-logging
otherwise you'll need to restart the FIM service after enabling tracing
https://social.technet.microsoft.com/wiki/contents/articles/10225.how-to-enable-fim-service-tracing.aspx

We need verbose logging on, and then attempt the request from your code, and send me the logs to ryan@lithnet.io

**Comment by hoetz** [comment]
I am on 4.4.1749.0 so I think this might work. Will take a look at this ASAP.

**Comment by ryannewington** [comment]
@hoetz just checking in to see if you had any luck getting those logs

**Comment by hoetz** [comment]
@ryannewington not yet since I am occupied with another project at the moment :(
Hope to return to MIM very soon

**Comment by hoetz** [comment]
Closing this since I am currently unable to investigate any further.
