### ISSUE TITLE
Most efficient way to test connection to MIM

### ISSUE THREAD

**Issue by Ruffio** [lithnet/resourcemanagement-client#18]
I'm writting a web service that communicates with MIM using this client. In order to monitor and be proactive I want to test the connection to MIM on a regular basis, so the question is what is the most efficient way to test the connecivity to MIM?

Is it just to do the:
ResourceManagementClient client = new ResourceManagementClient();

or do I have to actually send a request? If so, which request is most efficient/takes least resources?

**Comment by ryannewington** [comment]
@Ruffio, from memory, you'll have to send a request. Something very light like what autosync does to check for new requests will do the job

string path = "/Request"
ISearchResultCollection r = c.GetResources(xpath, 1, new[] { "msidmCompletedTime" }, "msidmCompletedTime", false);

which will get at most 1 request and return only a single attribute. Note that the first time you create a client, it will retrieve the schema from the server, but subsequent creations won't do that. So just beware, as if there are connectivity issues, the first one will fail, but that doesn't mean future ones will.

**Comment by Ruffio** [comment]
Thanks
