### ISSUE TITLE
Exception in ServiceFaultTranslator when fault does not have details

### ISSUE THREAD

**Issue by dzaslavskiy** [lithnet/resourcemanagement-client#19]
GetExceptionFromFaultMessage in ServiceFaultTranslator at line 37 fault.GetReaderAtDetailContents() is throwing a InvalidOperationException on a fault with fault details = null. This leads to the real error from FIM Service being hidden by the InvalidOperationException

**Comment by ryannewington** [comment]
@dzaslavskiy thanks for reporting this. Are you able to provide me the details of the real error from the event log of the FIM service box?

**Comment by dzaslavskiy** [comment]
In event log I have "System.InvalidOperationException: Invalid token in XPath expression."
The fault reason is "cannot filter as requested" and the Subcode name is CannotProcessFilter.

**Comment by ryannewington** [comment]
@dzaslavskiy you'll find this fixed in nuget package version 1.0.6993.

Thanks for reporting the issues.
