### ISSUE TITLE
Porting to dotnet core 2.1+

### ISSUE THREAD

**Issue by nemrism** [lithnet/resourcemanagement-client#20]
Hi @ryannewington 

Could you share your actual roadmap?
We already use your library in one of our project and would like to fully migrate it using dotnet core 2.1+.
Do you think it could be feasible to make this library for such a use case?

Best,
Aymeric

**Comment by ryannewington** [comment]
Hi @nemrism 

Unfortunately the parts of the .net framework (wcf wshttpcontextbinding and Kerberos auth) used to communicate with the fim service have not been ported to .net core. Until that changes, it won’t be possible to talk to the fim service using anything except .net framework. 

If and when the .net team implement support for the needed features in net core, migrating will be straightforward for me to do. 

Ryan
