### ISSUE TITLE
Version compatability

### ISSUE THREAD

**Issue by ketilrs** [lithnet/resourcemanagement-client#23]
Hi,

I'm developing a MIM Connector for a customer who is running MIM Sync Engine version 4.6.421.0
There is an issue getting the resourcemanagement-client to run with the bundled Microsoft.ResourceManagement.dll without adding it to the GAC, but that creates all sorts of other problems.
Would it be possible to have a build that targets the dll for the 4.6.421.0 version?

Best regards,
Ketil Roaas-Sedal

**Comment by ryannewington** [comment]
Hi @ketilrs 

This should be solvable with a binding redirect in the host executable's `.config` file that redirects to the version you have installed.

**Comment by ketilrs** [comment]
Hi @ryannewington 

Thank you for your quick reply.
I did try binding redirect initially in miiserver.exe.config, but that did not seem to work.
 <bindingRedirect oldVersion="4.1.3451.0" newVersion="4.6.421.0" />
Also, I'm worried that this might have unintended consequences for other parts/MAs

Best regards,
Ketil Roaas-Sedal

**Comment by ryannewington** [comment]
Binding redirects are safe. They basically say "you are not going to find version A, B, C on this system, so if you are looking for them, use version X instead"

If the MA hosted out-of-process? If so, you'd need to use dllhost.exe.config.

This is a very comment issue with MIM, and this is the standard way to resolve it
