### ISSUE TITLE
Can we directly add Email's instead of member object id to the MIM group object?

### ISSUE THREAD

**Issue by ravi4s45** [lithnet/resourcemanagement-client#24]
I am trying to add bulk users to the distribution list using [resourcemanagement-client] but everytime I need to fetch the member object in order to get object id to add it as the members of that group object which is a time consuming process,

Can we directly add Email without the need of object id, this will saves a lot of time since need to add thousands of users?

else can we reduce the api calls to get the member object by calling it in batches
 ResourceObject[] member = client.GetResourceByKey("Person", "Email", EmailsArray); I am getting error here

Or is there any other efficient way to add users to the MIM group using [resourcemanagement-client]

`ResourceManagementClient client = new ResourceManagementClient(baseAddress,networkCredential);
            ResourceObject group = client.GetResourceByKey("Group", "AccountName", "Test Distribution List");
            ResourceObject member = client.GetResourceByKey("Person", "Email", "xyz@abc.com");
            group.Attributes["ExplicitMember"].AddValue(member.ObjectID); `

**Comment by ryannewington** [comment]
You can't avoid getting the resource ID for adding to the group, but make sure you use the 'attributesToGet' overload whereever possible, and specify that you only want the objectID - that will be much faster.

Depending on the size of the data store, you should be able to enumerate all users email and object IDs with a single call at the start of large bulk operations, and add them to a dictionary for quick lookup.

The key to performance when using MIM, is only ask for the attributes you need, and batch operations wherever possible

**Comment by ravi4s45** [comment]
Thanks for the quick reply @ryannewington.
I am doing the batch operations and found a way to get multiple users at once 
```
string xpathFilter = "/Person[Email='email1' or Email='email2' or ... or Email='email25']";
IEnumerable<string> attributesToGet = new List<string>{ "ObjectID"};
ISearchResultCollection searchResults = GetResources(xpathFilter, attributesToGet);
```
But I am able to get the result for around 25 users at once If i increase the size of my filter then operation keep on going and does not give the result.

Is there a way to get a lot of users object around 100 or more at once?
Thanks!

**Comment by ryannewington** [comment]
@ravi4s45 unfortunately not

**Comment by ravi4s45** [comment]
Okay, Thanks!
