### ISSUE TITLE
Index out of Range exception while hitting Lithnet FIM client using WrapperService

### ISSUE THREAD

**Issue by Prasanthi28** [lithnet/resourcemanagement-client#6]
Hi,
We are using Lithnet FIM Client to search the user list from FIM using 3 attributes from SOAP UI. When we tested with one transaction it is working fine. But when we perform bulk load testing i.e. hitting 10 to 15 requests parallel, at some point of time it is giving Index Out of Range exception.

Kindly let us know how to handle multiple request to avoid index out of range exception.

**Comment by ryannewington** [comment]
Hi @Prasanthi28, sorry to hear you are having trouble with the client. Parallel requests are certainly supported, provided you create a new instance of the resourcemanagementclient for each thread. You can wrap the client in a using statement to make things easier. If you are still having troubles, can you send me the stack trace of the exception, and a way to reproduce if that's possible and ill take a look.

**Comment by ryannewington** [comment]
@Prasanthi28 I'm going to close this request for now. Feel free to reopen if you are still having issues
