### ISSUE TITLE
Proposition - Adding convenience methods for setting attributes

### ISSUE THREAD

**Issue by andersjarl** [lithnet/resourcemanagement-client#9]
Hi,
Setting attribute values is done today like this:
``resourceObject.Attributes[attributeName].SetValue(value);``

I am proposing to either add methods directly to ResourceObject or to have extensionmethods to be able to set, add, remove etc like this:
``resourceObject.SetValue(attributeName, value);``
``resourceObject.HasValue(attributeName, value);``
``resourceObject.RemoveValue(attributeName, value);``
``resourceObject.AddValue(attributeName, value);``

**Example of one of these directly in ResourceObject.cs:**
``public void SetValue(string attributeName, object value)``
``{``
``    Attributes[attributeName].SetValue(value);``
``}``

**Example as extensionmethod to ResourceObject with the additional functionality to be able to check for null:**
``public static void SetValue(this ResourceObject rObject, string attributeName, object value)``
``{``
``    if (rObject != null)``
``        rObject.Attributes[attributeName].SetValue(value);``
``}``

This is only a proposition. I am implementing this as extensionmethods as it is now, but it would be nice to have in the framework. :)

Regards
Anders

**Comment by ryannewington** [comment]
Hi @andersjarl. Good idea. Want to add them as extensions to this file and submit a pr?
https://github.com/lithnet/resourcemanagement-client/blob/master/src/Lithnet.ResourceManagement.Client/Utilities/Extensions.cs

**Comment by andersjarl** [comment]
Hi @ryannewington.
I've added them to the file you pointed me to. It is in the same Pull Request as the initial one.

**Comment by ryannewington** [comment]
Merged PR #10 into master branch

**Comment by ryannewington** [comment]
Hi @andersjarl,

The binaries have now been updated on nuget.

Thanks for the contributions!

Ryan

**Comment by andersjarl** [comment]
No problem @ryannewington and thanks for the mention in the release notes. :)

/Anders

**Comment by mcarahul22** [comment]
resourceObject.Attributes[attributeName].SetValue(value) is not working with multiple values for multi value attributes..
If I use ResourceID with comma seperate only first value is resolved and accepted/stamped...also tried with unique  identifies(accountname) with semi comma and commas....
How I can use addvalues for multiple value attribute..
